# localhost ルートに設定
<VirtualHost *:443>
    ServerName localhost
    DocumentRoot /var/www/html
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/server.crt
    SSLCertificateKeyFile /etc/ssl/private/server.key
</VirtualHost>

# --- project-a.localの場合 ---
<VirtualHost *:80>
    ServerName project-a.local
    RewriteEngine On
    RewriteRule ^ https://project-a.local:8443%{REQUEST_URI} [R=301,L,NE]
</VirtualHost>

<VirtualHost *:443>
    ServerName project-a.local
    DocumentRoot /var/www/html/project-a
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/server.crt
    SSLCertificateKeyFile /etc/ssl/private/server.key
</VirtualHost>
